### ISSUE TITLE
Detecting custom compiled opcodes

### ISSUE THREAD

**Issue by eddyc** [nwhetsell/linter-csound#10]
One of my own compiled opcodes isn't being picked up by the linter, csound compiles and runs fine with the opcode but for some reason the token for the opcode name is showing up as an error. I have a different opcode that I have compiled that is parsed correctly. Just wondering how I can fix this? Do I need to re-install the node csound-api or something?

**Comment by nwhetsell** [comment]
Probably. If you enter in Terminal

```sh
node --eval '
const csound = require("csound-api");
const Csound = csound.Create();
const opcodeList = [];
csound.NewOpcodeList(Csound, opcodeList);
opcodeList.forEach(opcode => console.log(opcode.opname));
'
```

does the opcode appear in the output? If not, quit Atom, `cd` to the linter-csound folder (probably ~/atom/packages/linter-csound), run

```sh
npm rebuild csound-api
```

restart Atom, and see if that fixes it.

**Comment by nwhetsell** [comment]
:grimacing: I told you the wrong folder. There should be a period in front of ‘atom’, making it ~/.atom/packages/linter-csound.

**Comment by eddyc** [comment]
It actually appears in the list of opcodes when running that node code. I tried rebuilding csound-api anyway but that didn't solve it.

**Comment by nwhetsell** [comment]
Huh, weird. What’s the text of the error message?

**Comment by eddyc** [comment]
Error: expected expression. I think I know what the problem is, as the opcode is currently in development it does not define any inputs or outputs, so I think this is what is triggering the error, I simply have the name of the opcode on the line, this works in Csound though. If I add a dummy output it throws no errors.

**Comment by nwhetsell** [comment]
Ah, that’s it.

By way of explanation, the Csound language has an ambiguity. Say you have two identifiers on one line:

```csound
identifier1 identifier2
```

That could be

```csound
opcodeWithNoOutputs iInput
```

or

```csound
iOutput opcodeWithNoInputs
```

To determine which of those is correct, linter-csound, and Csound itself, keep track of opcodes that have no outputs and treat them a little differently. The upshot is that Csound needs some information about opcode inputs and outputs to parse orchestras correctly. (Although I’m not sure how Csound can run an orchestra with an opcode that has no inputs or outputs, unless Csound actually allows that; linter-csound [doesn’t](https://github.com/nwhetsell/linter-csound/blob/master/lib/csound-parser/orchestra.jison#L308-L337), and I’m not sure there _are_ any opcodes in Csound with no inputs or outputs.)
