### ISSUE TITLE
Multiline strings using curly braces error

### ISSUE THREAD

**Issue by eddyc** [nwhetsell/linter-csound#4]
This:

```csound
opcode simple, a, ki

    pyruni {{
        from math import log
        cent = log(x,2)*1200
        print cent
    }}
    
  kamp, ipitch xin

  aout vco2 kamp, ipitch

  xout aout

endop
```

Gives the error:

> Invalid Statement

**Comment by nwhetsell** [comment]
On what line is the error?

**Comment by eddyc** [comment]
Line 3:12

**Comment by nwhetsell** [comment]
This is incredibly odd. I can’t reproduce this for the life of me.

For consistency’s sake, I just published an update to linter-csound with my most recent changes, but these were just [updating things for Linter v2](https://steelbrain.me/2017/03/13/linter-v2-released.html).

Can you attach the actual file you’re working with to a comment on this issue? (If GitHub complains, just attach a file with a `txt` extension.) Also, what operating system are you using?

**Comment by eddyc** [comment]
macOS 10.12.4
[simple.udo.txt](https://github.com/nwhetsell/linter-csound/files/962287/simple.udo.txt)

**Comment by nwhetsell** [comment]
If you run in Terminal

```sh
csound --list-opcodes2
```

does `pyruni` appear in the list?

**Comment by eddyc** [comment]
No it doesn't, I think this was my error in misunderstanding how the linter worked. I had built Csound myself and obviously didn't enable python support. Sorry for the noise.
Ed

**Comment by nwhetsell** [comment]
No worries! I think I’ll add a note to the README that linter-csound uses the opcodes that are actually installed to do linting (especially since [language-csound](https://atom.io/packages/language-csound) highlights `pyruni` as an opcode whether Python opcodes are available or not).
