### ISSUE TITLE
Linter not reporting any errors

### ISSUE THREAD

**Issue by eddyc** [nwhetsell/linter-csound#5]
The following csd should report an error on line 13:
```csound-csd
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 256
nchnls = 1
0dbfs = 1

instr main
	aOut vco2 0.4, 440
	out aUndefined
endin

</CsInstruments>
</CsoundSynthesizer>
```
It seems that the linter is not successfully parsing the file. linter-csound version 0.2.8, Atom version 1.17.2

**Comment by nwhetsell** [comment]
I’ll leave this on my radar, but while linter-csound is successfully parsing that code, it’s not building a symbol table sophisticated enough to know that `aUndefined` is undefined.

**Comment by nwhetsell** [comment]
This should be fixed in commit d87a1e73bbff56be5079b2df1c94d28e4a9c480f. Can you reproduce this in linter-csound 0.3.0?

**Comment by eddyc** [comment]
Yes, getting the error 'Use of undefined variable aUndefined' now.

**Comment by nwhetsell** [comment]
That’s the expected behavior, right?

**Comment by eddyc** [comment]
Yeah absolutely, that works great now
