### ISSUE TITLE
Fsig variables error

### ISSUE THREAD

**Issue by eddyc** [nwhetsell/linter-csound#7]
I'm getting the linter error for fsigs : Variable name 'fsig' does not begin with type characters.
edit: Forgot to mention this is with 0.3.1

**Comment by nwhetsell** [comment]
Can you attach a small example showing the issue?

**Comment by nwhetsell** [comment]
Never mind; for reasons unknown I was using `p` instead of `f` for this storage-type prefix. This should be fixed in e9c2326c6165f13495d8d5708d0783db56f0cc58, and linter-csound v0.3.2 includes this patch.
